
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import App from "next/app";
import AppBar from "@/components/AppBar";
import Footer from "@/components/Footer";
import { usePathname } from "next/navigation";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Restaurante",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      
      <body className={inter.className}>
        <AppBar/>    


        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          {children}
        </div>

        <Footer/>
      </body>

    </html>



  );
}
